# Generated by scripts/prepare-release.mjs; edit the template instead.
# CLI source commit: 6dd32fc8fa8db96c347fd4502bd18ad2757eb236
class Heroku < Formula
  desc "Manage Heroku apps with dentarg's local fixes"
  homepage "https://github.com/dentarg/heroku-cli"
  url "https://github.com/dentarg/homebrew-tap/releases/download/v11.11.0-1/heroku-11.11.0.tgz"
  sha256 "4f387ba9f81f580a0217d0ef5252970c5668d5a0036aa03e70ea4094e0c5b4ba"
  license "ISC"
  revision 1

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    # tar-stream includes Bare runtime binaries that are unused by Node.js.
    libexec.glob("lib/node_modules/heroku/node_modules/bare-*/prebuilds").each(&:rmtree)

    (bin/"heroku").write_env_script libexec/"bin/heroku",
      PATH:                          "#{formula_opt_bin("node")}:$PATH",
      HEROKU_DISABLE_AUTOUPDATE:     "true",
      HEROKU_SKIP_NEW_VERSION_CHECK: "true",
      HEROKU_UPDATE_INSTRUCTIONS:    "update with: brew upgrade dentarg/tap/heroku"

    completions = libexec/"lib/node_modules/heroku/autocomplete-scripts/brew"
    bash_completion.install completions/"bash" => "heroku"
    zsh_completion.install completions/"zsh/_heroku"
  end

  def caveats
    <<~EOS
      To leave your global Git configuration untouched, add this to your shell configuration:
        export HEROKU_DISABLE_GIT_CONFIG=1

      Update this build with:
        brew upgrade dentarg/tap/heroku
    EOS
  end

  test do
    ENV["HEROKU_DISABLE_GIT_CONFIG"] = "1"
    ENV["DISABLE_TELEMETRY"] = "true"
    (testpath/".gitconfig").write "# user-managed Git configuration\n", mode: "a"
    original_git_config = (testpath/".gitconfig").read

    assert_match "heroku/#{version}", shell_output("#{bin}/heroku --version")
    commands = JSON.parse(shell_output("#{bin}/heroku commands --json"))
    assert commands.any? { |command| command.fetch("id") == "apps" }
    assert_equal original_git_config, (testpath/".gitconfig").read
  end
end
